"""
Script sửa lỗi encoding tiếng Việt trong file text
Sửa các lỗi encoding phổ biến từ PDF
"""

import re
import sys

def fix_vietnamese_encoding(text):
    """Sửa lỗi encoding tiếng Việt"""
    
    # Dictionary các lỗi encoding phổ biến
    fixes = [
        # Lỗi dấu cơ bản
        (r'Cöng', 'Công'),
        (r'cöng', 'công'),
        (r'Trñ', 'Trí'),
        (r'trñ', 'trí'),
        (r'Viïåt', 'Việt'),
        (r'viïåt', 'việt'),
        (r'Viïtå', 'Việt'),
        (r'viïtå', 'việt'),
        (r'baãn', 'bản'),
        (r'quyïìn', 'quyền'),
        (r'xuêët', 'xuất'),
        (r'xuêtë', 'xuất'),
        (r'banã', 'bản'),
        (r'phaát', 'phát'),
        (r'phatá', 'phát'),
        (r'haânh', 'hành'),
        (r'hanâ h', 'hành'),
        (r'hanâ g', 'hàng'),
        (r'tiïëng', 'tiếng'),
        (r'ÀANÁ H', 'ĐÁNH'),
        (r'Àaánh', 'Đánh'),
        (r'CÙPÆ', 'CẮP'),
        (r'Cùpæ', 'Cắp'),
        (r'TÛÚNÃ G', 'TƯỞNG'),
        (r'Tûúãng', 'Tưởng'),
        (r'Tûúnã g', 'Tưởng'),
        (r'Nhûnä g', 'Những'),
        (r'nhûnä g', 'những'),
        (r'giupá', 'giúp'),
        (r'banå', 'bạn'),
        (r'thanâ h', 'thành'),
        (r'àocå', 'đọc'),
        (r'camã', 'cảm'),
        (r'thêyë', 'thấy'),
        (r'cuönë', 'cuốn'),
        (r'sacá h', 'sách'),
        (r'cuaã', 'của'),
        (r'biïtë', 'biết'),
        (r'rùnç g', 'rằng'),
        (r'rùçng', 'rằng'),
        (r'khamá', 'khám'),
        (r'pha á', 'phá'),
        (r'y á', 'ý'),
        (r'co á', 'có'),
        (r'thï í', 'thể'),
        (r'hún', 'hơn'),
        (r'viïcå', 'việc'),
        (r'têtë', 'tất'),
        (r'ca ã', 'cả'),
        (r'moiå', 'mọi'),
        (r'khña', 'khía'),
        (r'canå h', 'cạnh'),
        (r'vï ì', 'về'),
        (r'vaâ', 'và'),
        (r'Thûúng', 'Thương'),
        (r'thûúng', 'thương'),
        (r'hiïuå', 'hiệu'),
        (r'yïuë', 'yếu'),
        (r'tö ë', 'tố'),
        (r'se ä', 'sẽ'),
        (r'thucá', 'thúc'),
        (r'àêyí', 'đẩy'),
        (r'ngayâ', 'ngày'),
        (r'mötå', 'một'),
        (r'luön', 'luôn'),
        (r'tiïnë', 'tiến'),
        (r'phña', 'phía'),
        (r'trûúcá', 'trước'),
        (r'truéc', 'trước'),
        (r'hiïnå', 'hiện'),
        (r'hiïån', 'hiện'),
        (r'àang', 'đang'),
        (r'laâ', 'là'),
        (r'giamá', 'giám'),
        (r'giaám', 'giám'),
        (r'àöcë', 'đốc'),
        (r'àöëc', 'đốc'),
        (r'àiïuì', 'điều'),
        (r'quanã', 'quản'),
        (r'quaãn', 'quản'),
        (r'lyá', 'lý'),
        (r'Ly á', 'Lý'),
        (r'Ngên', 'Ngân'),
        (r'nganâ h', 'ngân hàng'),
        (r'Àêuì', 'Đầu'),
        (r'àêuì', 'đầu'),
        (r'Tû', 'Tư'),
        (r'Va â', 'Và'),
        (r'Taiâ', 'Tài'),
        (r'taiâ', 'tài'),
        (r'Sanã', 'Sản'),
        (r'têåp', 'tập'),
        (r'àoaân', 'đoàn'),
        (r'Cuâng', 'Cùng'),
        (r'cuâng', 'cùng'),
        (r'vúái', 'với'),
        (r'nùm', 'năm'),
        (r'cêpë', 'cấp'),
        (r'khacá', 'khác'),
        (r'öng', 'ông'),
        (r'chõu', 'chịu'),
        (r'tracá h', 'trách'),
        (r'nhiïmå', 'nhiệm'),
        (r'phöië', 'phối'),
        (r'toanâ', 'toàn'),
        (r'cêuì', 'cầu'),
        (r'cacá', 'các'),
        (r'taiå', 'tại'),
        (r'quöcë', 'quốc'),
        (r'sö ë', 'số'),
        (r'lûúnå g', 'lượng'),
        (r'lïn', 'lên'),
        (r'àïnë', 'đến'),
        (r'triïuå', 'triệu'),
        (r'ngûúiâ', 'người'),
        (r'Ngoaiâ', 'Ngoài'),
        (r'conâ', 'còn'),
        (r'nùmæ', 'nắm'),
        (r'giû ä', 'giữ'),
        (r'võ', 'vị'),
        (r'quaãng', 'quảng'),
        (r'caáo', 'cáo'),
        (r'cunä g', 'cùng'),
        (r'nhû', 'như'),
        (r'Trûúcá', 'Trước'),
        (r'lamâ', 'làm'),
        (r'chuã', 'chủ'),
        (r'tõch', 'tịch'),
        (r'baná', 'bán'),
        (r'le ã', 'lẻ'),
        (r'kiïm', 'kiêm'),
        (r'chñnh', 'chính'),
        (r'chuyïn', 'chuyên'),
        (r'lônh', 'lĩnh'),
        (r'vûcå', 'vực'),
        (r'dõch', 'dịch'),
        (r'vu å', 'vụ'),
        (r'thúiâ', 'thời'),
        (r'àa ä', 'đã'),
        (r'thûcå', 'thực'),
        (r'chiïnë', 'chiến'),
        (r'caoá', 'cao'),
        (r'sû ã', 'sử'),
        (r'dunå g', 'dụng'),
        (r'hònh', 'hình'),
        (r'anã h', 'ảnh'),
        (r'cûuå', 'cựu'),
        (r'tùng', 'tăng'),
        (r'àaná g', 'đáng'),
        (r'kï í', 'kỹ'),
        (r'nguönì', 'nguồn'),
        (r'quy ä', 'quỹ'),
        (r'gopá', 'góp'),
        (r'phênì', 'phần'),
        (r'mú ã', 'mở'),
        (r'rönå g', 'rộng'),
        (r'giúiá', 'giới'),
        (r'chûná g', 'chứng'),
        (r'khoaná', 'khoán'),
        (r'choná g', 'chóng'),
        (r'àûa', 'đưa'),
        (r'trú ã', 'trở'),
        (r'nha â', 'nhà'),
        (r'cung cêpë', 'cung cấp'),
        (r'phên', 'phần'),
        (r'nûãa', 'nửa'),
        (r'thúâi', 'thời'),
        (r'àoá', 'đó'),
        (r'taåo', 'tạo'),
        (r'mònh', 'mình'),
        (r'chöî', 'chỗ'),
        (r'àûáng', 'đứng'),
        (r'tñn', 'tín'),
        (r'àöíi', 'đổi'),
        (r'múái', 'mới'),
        (r'lêìn', 'lần'),
        (r'baãy', 'bảy'),
        (r'cöång', 'cộng'),
        (r'taác', 'tác'),
        (r'troâ', 'trò'),
        (r'lûúåc', 'lược'),
        (r'cêìu', 'cầu'),
        (r'tûâng', 'từng'),
        (r'nghô', 'nghĩ'),
        (r'chùèng', 'chẳng'),
        (r'giúâ', 'giờ'),
        (r'cêìn', 'cần'),
        (r'àïën', 'đến'),
        (r'quyïín', 'quyển'),
        (r'saách', 'sách'),
        (r'naâo', 'nào'),
        (r'vïì', 'về'),
        (r'àoåc', 'đọc'),
        (r'àûúåc', 'được'),
        (r'cuöën', 'cuốn'),
        (r'cêím', 'cẩm'),
        (r'hêëp', 'hấp'),
        (r'dêîn', 'dẫn'),
        (r'suác', 'sức'),
        (r'pha', 'pha'),
        # Thêm các lỗi khác
        (r'hy vonå g', 'hy vọng'),
        (r'thuá võ', 'thú vị'),
        (r'vúiá', 'với'),
        (r'ú ã', 'ở'),
        (r'bao quatá', 'bao quát'),
        (r'khña canå h', 'khía cạnh'),
        (r'yïuë tö ë', 'yếu tố'),
        (r'thucá àêyí', 'thúc đẩy'),
        (r'ngayâ mötå', 'ngày một'),
        (r'luön tiïnë', 'luôn tiến'),
        (r'vï ì phña', 'về phía'),
        (r'giamá àöcë', 'giám đốc'),
        (r'àiïuì hanâ h', 'điều hành'),
        (r'quanã lyá', 'quản lý'),
        (r'thûúng hiïåu', 'thương hiệu'),
        (r'Ngên Hanâ g', 'Ngân Hàng'),
        (r'Àêuì Tû', 'Đầu Tư'),
        (r'Quanã Ly á', 'Quản Lý'),
        (r'Taiâ Sanã', 'Tài Sản'),
        (r'têåp àoaân', 'tập đoàn'),
        (r'Cuâng vúái', 'Cùng với'),
        (r'nùm giaám', 'năm giám'),
        (r'àöëc quanã', 'đốc quản'),
        (r'ly á cêpë', 'lý cấp'),
        (r'cao khacá', 'cao khác'),
        (r'öng chõu', 'ông chịu'),
        (r'tracá h nhiïmå', 'trách nhiệm'),
        (r'àiïuì phöië', 'điều phối'),
        (r'viïcå quanã', 'việc quản'),
        (r'ly á thûúng', 'lý thương'),
        (r'hiïuå toanâ', 'hiệu toàn'),
        (r'cêuì cho', 'cầu cho'),
        (r'têtë ca ã', 'tất cả'),
        (r'cacá nganâ', 'các ngân'),
        (r'h kinh doanh', 'h kinh doanh'),
        (r'cuaã têpå', 'của tập'),
        (r'àoanâ Citigroup', 'đoàn Citigroup'),
        (r'taiå hún', 'tại hơn'),
        (r'100 quöcë', '100 quốc'),
        (r'gia, vúiá', 'gia, với'),
        (r'sö ë lûúnå g', 'số lượng'),
        (r'khacá h hanâ g', 'khách hàng'),
        (r'lïn àïnë', 'lên đến'),
        (r'200 triïuå', '200 triệu'),
        (r'ngûúiâ .', 'người.'),
        (r'Ngoaiâ ra', 'Ngoài ra'),
        (r'Steve conâ', 'Steve còn'),
        (r'nùmæ giû ä', 'nắm giữ'),
        (r'võ trñ', 'vị trí'),
        (r'quaãn lyá', 'quản lý'),
        (r'thûúng hiïåu', 'thương hiệu'),
        (r'vaâ quaãng', 'và quảng'),
        (r'caáo cho', 'cáo cho'),
        (r'Ngên haâng', 'Ngân hàng'),
        (r'Citigroup cunä g', 'Citigroup cùng'),
        (r'nhû cacá', 'như các'),
        (r'nganâ h', 'ngân hàng'),
        (r'kinh doanh', 'kinh doanh'),
        (r'vúiá thûúng', 'với thương'),
        (r'hiïuå Smith', 'hiệu Smith'),
        (r'Barney cuaã', 'Barney của'),
        (r'têåp àoaân', 'tập đoàn'),
        (r'Citigroup.', 'Citigroup.'),
        (r'Trûúcá khi', 'Trước khi'),
        (r'lamâ viïcå', 'làm việc'),
        (r'cho Citigroup', 'cho Citigroup'),
        (r'Steve giû ä', 'Steve giữ'),
        (r'chûcá chuã', 'chức chủ'),
        (r'tõch nganâ', 'tịch ngân'),
        (r'h kinh doanh', 'h kinh doanh'),
        (r'baná le ã', 'bán lẻ'),
        (r'kiïm giamá', 'kiêm giám'),
        (r'àöcë Marketing', 'đốc Marketing'),
        (r'cuaã têåp', 'của tập'),
        (r'àoaân taiâ', 'đoàn tài'),
        (r'chñnh Fidelity.', 'chính Fidelity.'),
    ]
    
    # Áp dụng các sửa lỗi
    for pattern, replacement in fixes:
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    
    return text

def main():
    if len(sys.argv) < 2:
        print("Sử dụng: python fix_vietnamese_encoding.py <file_input> [file_output]")
        print("Ví dụ: python fix_vietnamese_encoding.py 2_extracted.txt 2_extracted_fixed.txt")
        return
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file.replace('.txt', '_fixed.txt')
    
    try:
        # Đọc file với encoding UTF-8
        with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        print(f"Đang sửa lỗi encoding trong file: {input_file}")
        print(f"Kích thước file: {len(content)} ký tự")
        
        # Sửa lỗi encoding
        fixed_content = fix_vietnamese_encoding(content)
        
        # Lưu file đã sửa
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(fixed_content)
        
        print(f"✅ Đã sửa xong và lưu vào: {output_file}")
        print(f"Đã sửa {len(content) - len(fixed_content)} thay đổi")
        
    except Exception as e:
        print(f"❌ Lỗi: {e}")

if __name__ == "__main__":
    main()



